sudo: required
dist: trusty
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
# command to install dependencies
install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      pip install Frcwp;
    elif [[ "$TRAVIS_PYTHON_VERSION" == "3.4" ]]; then
      pip Frcwp;
    elif [[ "$TRAVIS_PYTHON_VERSION" == "3.5" ]]; then
      pip install Frcwp;
    fi

# command to run tests
script:
  - python -m unittest discover -s tests;